"""Browser-based API client — uses patchright to make requests from a real browser context.

stoken is generated by the browser's JS environment automatically, eliminating expiration issues.
Used for high-risk operations: search, recommend, greet, batch-greet.
"""
import random
import time
from collections import deque

from patchright.sync_api import sync_playwright

from boss_agent_cli.api import endpoints

HOME_URL = "https://www.zhipin.com/"


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch)."""

	def __init__(self, cookies: dict, user_agent: str, *, delay: tuple[float, float] = (1.5, 3.0)):
		self._delay = delay
		self._last_request_time = 0.0
		self._recent_times: deque[float] = deque(maxlen=12)
		self._pw = None
		self._browser = None
		self._context = None
		self._page = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False

	def _ensure_started(self):
		if self._started:
			return
		self._pw = sync_playwright().start()
		self._browser = self._pw.chromium.launch(headless=True)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._context.add_cookies([
			{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
			for name, value in self._cookies.items()
		])
		self._page = self._context.new_page()
		self._page.goto(HOME_URL, wait_until="domcontentloaded")
		self._page.wait_for_load_state("networkidle")
		self._started = True

	# ── Anti-detection delays ────────────────────────────────────────

	def _wait(self):
		elapsed = time.time() - self._last_request_time
		mean = sum(self._delay) / 2
		std = (self._delay[1] - self._delay[0]) / 4
		base_sleep = max(0, random.gauss(mean, std) - elapsed)

		if random.random() < 0.05:
			base_sleep += random.uniform(2.0, 5.0)

		burst = self._burst_penalty()
		total = max(0, base_sleep + burst)
		if total > 0:
			time.sleep(total)

	def _burst_penalty(self) -> float:
		if not self._recent_times:
			return 0.0
		now = time.time()
		recent_15s = sum(1 for ts in self._recent_times if now - ts <= 15)
		recent_45s = sum(1 for ts in self._recent_times if now - ts <= 45)
		if recent_45s >= 6:
			return random.uniform(4.0, 7.0)
		if recent_15s >= 3:
			return random.uniform(1.2, 2.8)
		return 0.0

	def _mark_request(self):
		now = time.time()
		self._last_request_time = now
		self._recent_times.append(now)

	# ── Core request via browser fetch() ─────────────────────────────

	def request(self, method: str, url: str, *, params: dict | None = None, data: dict | None = None) -> dict:
		self._ensure_started()
		self._wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		result = self._page.evaluate("""
			async ({method, url, params, data, referer}) => {
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'Referer': referer,
							'X-Requested-With': 'XMLHttpRequest',
						},
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					return {code: -1, message: e.message, zpData: {}};
				}
			}
		""", {"method": method, "url": url, "params": params or {}, "data": data, "referer": referer})

		self._mark_request()
		return result

	# ── Lifecycle ────────────────────────────────────────────────────

	def close(self):
		if self._browser:
			self._browser.close()
		if self._pw:
			self._pw.stop()
		self._started = False

	def __enter__(self):
		return self

	def __exit__(self, *args):
		self.close()
