"""Browser-based API client — uses patchright to make requests from a real browser context.

stoken is generated by the browser's JS environment automatically, eliminating expiration issues.
Used for high-risk operations: search, recommend, greet, batch-greet.

Supports two modes:
  1. CDP mode (preferred): connects to user's existing Chrome via DevTools Protocol
  2. Patchright mode (fallback): launches a headless Chromium instance
"""
import random
import sys
import time

from patchright.sync_api import sync_playwright

from boss_agent_cli.api import endpoints
from boss_agent_cli.api.throttle import RequestThrottle

HOME_URL = "https://www.zhipin.com/"
CDP_DEFAULT_URL = "http://localhost:9222"


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch).

	Tries CDP connection to user's Chrome first; falls back to headless patchright.
	"""

	def __init__(self, cookies: dict, user_agent: str, *, delay: tuple[float, float] = (1.5, 3.0), cdp_url: str | None = None):
		self._throttle = RequestThrottle(delay)
		self._pw = None
		self._browser = None
		self._context = None
		self._page = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False
		self._cdp_url = cdp_url
		self._is_cdp = False

	def _ensure_started(self):
		if self._started:
			return
		self._pw = sync_playwright().start()

		# 优先尝试 CDP 连接用户 Chrome（真实指纹 + 天然登录态）
		if self._try_cdp():
			return

		# 降级：启动 headless patchright
		self._start_headless()

	def _try_cdp(self) -> bool:
		"""Try connecting to user's Chrome via CDP."""
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		try:
			self._browser = self._pw.chromium.connect_over_cdp(cdp_url)
			# CDP 模式下用默认上下文（即用户的浏览器上下文，带完整登录态）
			contexts = self._browser.contexts
			if contexts:
				self._context = contexts[0]
			else:
				self._context = self._browser.new_context()
			# 创建新 tab，不干扰用户现有标签页
			self._page = self._context.new_page()
			self._page.goto(HOME_URL, wait_until="domcontentloaded")
			self._page.wait_for_load_state("networkidle")
			self._started = True
			self._is_cdp = True
			print("[boss] CDP 连接成功，使用用户 Chrome（真实指纹）", file=sys.stderr)
			return True
		except Exception:
			# CDP 不可用，清理并返回 False
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
				self._browser = None
			return False

	def _start_headless(self):
		"""Fallback: launch headless patchright Chromium."""
		self._browser = self._pw.chromium.launch(headless=True)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._context.add_cookies([
			{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
			for name, value in self._cookies.items()
		])
		self._page = self._context.new_page()
		self._page.goto(HOME_URL, wait_until="domcontentloaded")
		self._page.wait_for_load_state("networkidle")
		self._started = True
		self._is_cdp = False
		print("[boss] CDP 不可用，降级到 headless patchright", file=sys.stderr)

	# ── Core request via browser fetch() ─────────────────────────────

	def request(self, method: str, url: str, *, params: dict | None = None, data: dict | None = None) -> dict:
		self._ensure_started()
		self._throttle.wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		result = self._page.evaluate("""
			async ({method, url, params, data, referer}) => {
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'Referer': referer,
							'X-Requested-With': 'XMLHttpRequest',
						},
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					return {code: -1, message: e.message, zpData: {}};
				}
			}
		""", {"method": method, "url": url, "params": params or {}, "data": data, "referer": referer})

		self._throttle.mark()
		return result

	# ── Lifecycle ────────────────────────────────────────────────────

	@property
	def is_cdp(self) -> bool:
		"""Whether this session is using CDP connection to user's Chrome."""
		return self._is_cdp

	def close(self):
		if self._is_cdp:
			# CDP 模式：只关闭我们创建的 tab，不关闭用户浏览器
			if self._page:
				try:
					self._page.close()
				except Exception:
					pass
		else:
			# Headless 模式：关闭整个浏览器实例
			if self._browser:
				self._browser.close()
		if self._pw:
			self._pw.stop()
		self._started = False

	def __enter__(self):
		return self

	def __exit__(self, *args):
		self.close()
